AWSTemplateFormatVersion: 2010-09-09

Description: First stack for my VPC

Metadata:

Parameters:

  VPCName: 
    Description: VPC-Teste
    Type: string
    Default: "VPC Stack"

Mappings:


  SubnetConfig:
   VPC: 
    CIDR: "10.0.0.0/16"
   Public0:
    CIDR: "10.0.1.0/24"
   Public1:
    CIDR: "10.0.1.0/24"
   Private0:
    CIDR: "10.0.1.0/24"      
   Private1:
    CIDR: "10.0.1.0/24" 

  AZRegions:
    us-east-1:
      AZs: ["a","b"]
    sa-east-1:
      AZs: ["a","b"]  


Conditions: 

Resources:

  VPC:
    Type: "AWS::ec2::VPC"
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostname: 'true'
      CidrBlock:
        FN::findInMap:
          - "SubnerConfig"
          - "VPC"
          - "CIDR"
      Tags:
        -
          Key: "Application"
          Value:
            Ref: AWS::StackName
        -
          Key: "Network"
          Value: "2 Tier VPC"
        -
          Key: "Name"
          Value:
            Ref: "VPCName"



    PublicSubnet0:
      Type: "AWS::EC2::Subnet"
      Properties:
        VPCId:
          Ref: "VPC"
        AvailabilityZone:
          FN::Sub:
            - `${AWS::Region}${AZ}`
            - AZ: !Select [0, !FindInMap ["AZRegions", !Ref "AWS::Region", "AZs"] ]  
        CidrBlock:
          FN::findInMap:
            - "SubnerConfig"
            - "VPC"
            - "CIDR"
        Tags:
          
          Key: "Name"
          Value: !Join
            - ''
            - - !Ref "VPCName"
              - '-public-'
              - !Select [0, !FindInMap ["AZRegions", !Ref "AWS::Region", "AZs"] ]

    PublicSubnet1:
      Type: "AWS::EC2::Subnet"
      Properties:
        VPCId:
          Ref: "VPC"
        AvailabilityZone:
          FN::Sub:
            - `${AWS::Region}${AZ}`
            - AZ: !Select [0, !FindInMap ["AZRegions", !Ref "AWS::Region", "AZs"] ]  
        CidrBlock:
          FN::findInMap:
            - "SubnerConfig"
            - "VPC"
            - "CIDR"
        Tags:
          
          Key: "Name"
          Value: !Join
            - ''
            - - !Ref "VPCName"
              - '-public-'
              - !Select [0, !FindInMap ["AZRegions", !Ref "AWS::Region", "AZs"] ]

    PrivateSubnet0:
      Type: "AWS::EC2::Subnet"
      Properties:
        VPCId:
          Ref: "VPC"
        AvailabilityZone:
          FN::Sub:
            - `${AWS::Region}${AZ}`
            - AZ: !Select [0, !FindInMap ["AZRegions", !Ref "AWS::Region", "AZs"] ]  
        CidrBlock:
          FN::findInMap:
            - "SubnerConfig"
            - "VPC"
            - "CIDR"
        Tags:
          
          Key: "Name"
          Value: !Join
            - ''
            - - !Ref "VPCName"
              - '-private-'
              - !Select [0, !FindInMap ["AZRegions", !Ref "AWS::Region", "AZs"] ]

    PrivateSubnet1:
      Type: "AWS::EC2::Subnet"
      Properties:
        VPCId:
          Ref: "VPC"
        AvailabilityZone:
          FN::Sub:
            - `${AWS::Region}${AZ}`
            - AZ: !Select [0, !FindInMap ["AZRegions", !Ref "AWS::Region", "AZs"] ]  
        CidrBlock:
          FN::findInMap:
            - "SubnerConfig"
            - "VPC"
            - "CIDR"
        Tags:
          
          Key: "Name"
          Value: !Join
            - ''
            - - !Ref "VPCName"
              - '-private-'
              - !Select [0, !FindInMap ["AZRegions", !Ref "AWS::Region", "AZs"] ]

    InternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
         Tags: -
          Key: "Application"
          Value:
            Ref: AWS::StackName
         -
          Key: "Network"
          Value: "2 Tier VPC"
         -
         Key: "Name"
         Value:
            Ref: "VPCName"

    GatewatTointernet:
      Type: "AWS::EC2::VPCGatewayAttachment"
      Properties:
        VPCId:
          Ref: "VPC"
      InternetGateway:
        Ref: "InternetGateway"    












Outputs: